require: rubocop-rspec

AllCops:
  DisplayCopNames: true

  Include:
    - '**/Appraisals'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'lib/generators/enumerate_it/enum/templates/**/*'
    - 'gemfiles/vendor/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ElseAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Naming/PredicateName:
  Exclude:
    - 'lib/enumerate_it/class_methods.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
