language: ruby

sudo: false

cache: bundler

script:
  - "ruby -e \"RUBY_VERSION == '2.6.4' ? system('bundle exec rubocop') : exit(0)\""
  - bundle exec rake spec

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

addons:
  code_climate:
    repo_token: 60e4a18e2a4bc86a98f92847f16756876c13d1e772058a9b3296643b04a697d7
